import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import ContactForm from './components/ContactForm'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
	return (
		<>
			<Head>
				<title>Next.js + Mailgun: Contact Form</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={`${styles.main} ${inter.className}`}>
				<ContactForm />
				<p>
					<a href="https://maxschmitt.me/posts/nextjs-contact-form">Read the blog post</a>
				</p>
			</main>
		</>
	)
}
